version: '3.5'

services:
  postgres:
    container_name: email_postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: 'email'
      PGDATA: /data/email_postgres
    volumes:
      - email_postgres:/data/postgres
    ports:
      - "5434:5432"
    restart: unless-stopped
  fake-smtp:
    image: munkyboy/fakesmtp
    container_name: fake-smtp
    ports:
      - "25:25"
    volumes:
      - ~/fake-smtp-emails:/var/mail
  fake-smtp-web:
    image: mjstewart/fakesmtp-web:1.2
    container_name: fake-smtp-web
    ports:
      - "60500:8080"
    volumes:
      - ~/fake-smtp-emails:/var/mail
    environment:
      - EMAIL_INPUT_DIR_POLL_RATE_SECONDS=10
    depends_on:
      - fake-smtp

volumes:
  email_postgres: