server:
  port: 8081

spring:
#  profiles: dev
  application:
    name: email-service
  kafka:
    consumer:
      bootstrap-servers: PLAINTEXT://127.0.0.1:9092
      topic: registration
      group-id: group-id_1
      auto-offset-reset: earliest
      sleep-in-ms: 0

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: "changeme"
    platform: postgres
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      jdbc-url: jdbc:postgresql://localhost:5433/email
      validation-timeout: 3000
      max-lifetime: 250000
    url: jdbc:postgresql://localhost:5433/email
  jpa:
    generate-ddl: false
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog-master.xml
    enabled: true

#  jpa:
#    generate-ddl: false
#    properties:
#      hibernate.temp.use_jdbc_metadata_defaults: false
#    open-in-view: false
##    properties:
##      hibernate:
##      dialect: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#  datasource:
#    url: jdbc:postgresql://localhost:5433/email
#    username: postgres
#    password: changeme
#    platform: postgres
#    hikari:
#      maximum-pool-size: 5
#      minimum-idle: 1
#      jdbc-url: jdbc:postgresql://localhost:5433/email
#      validation-timeout: 3000
#      max-lifetime: 250000
#  liquibase:
##    change-log: classpath:/db/changelog-master.xml
#    enabled: true
#    url: jdbc:postgresql://localhost:5433/email

  json:
    trusted:
      packages: "*"

  mail:
    host: localhost
    port: 25
    username:
    password:
    protocol: smtp
    tls: false
    properties.mail.smtp:
      auth: false
      starttls.enable: false
    from: me@localhost.com

#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#  datasource:
#    url: jdbc:postgresql://localhost:5433/email
#    username: postgres
#    password: changeme
#
#  liquibase:
#    change-log: classpath:/db/changelog-master.xml
#    enabled: true
#    url: jdbc:postgresql://localhost:5433/email
